language: cpp
sudo: required
dist: trusty
compiler:
  - gcc
addons:
  apt:
    packages:
      - libboost-dev
      - libboost-date-time-dev
      - build-essential
      - liblua5.1-0-dev
      - python-virtualenv
      - libgeoip-dev
      - geoip-database
before_script:
 - wget http://http.us.debian.org/debian/pool/main/libs/libsodium/libsodium-dev_1.0.0-1_amd64.deb http://http.us.debian.org/debian/pool/main/libs/libsodium/libsodium13_1.0.0-1_amd64.deb
 - dpkg-deb -x libsodium13_1.0.0-1_amd64.deb ${HOME}/libsodium
 - dpkg-deb -x libsodium-dev_1.0.0-1_amd64.deb ${HOME}/libsodium
 - rm libsodium13_1.0.0-1_amd64.deb libsodium-dev_1.0.0-1_amd64.deb
 - sed -i -e "s@/usr@${HOME}/libsodium/usr@" ${HOME}/libsodium/usr/lib/x86_64-linux-gnu/pkgconfig/libsodium.pc
 - export PKG_CONFIG_PATH=${HOME}/libsodium/usr/lib/x86_64-linux-gnu/pkgconfig
 - export LD_LIBRARY_PATH=${HOME}/libsodium/usr/lib/x86_64-linux-gnu
 - wget http://http.us.debian.org/debian/pool/main/g/getdns/libgetdns1_0.9.0-1_amd64.deb http://http.us.debian.org/debian/pool/main/g/getdns/libgetdns-dev_0.9.0-1_amd64.deb
 - dpkg-deb -x libgetdns-dev_0.9.0-1_amd64.deb ${HOME}/getdns
 - dpkg-deb -x libgetdns1_0.9.0-1_amd64.deb ${HOME}/getdns
 - rm libgetdns-dev_0.9.0-1_amd64.deb libgetdns1_0.9.0-1_amd64.deb
 - mkdir -p ${HOME}/getdns/usr/lib/pkgconfig
 - echo -e "prefix=${HOME}/getdns/usr\nexec_prefix=[prefix]\nlibdir=[exec_prefix]/lib/x86_64-linux-gnu\nincludedir=[prefix]/include\n\nName@ getdns\nVersion@ 0.5.1\nDescription@ A modern asynchronous DNS library\n\nLibs@ -L[libdir] -lgetdns\nCflags@ -I[includedir]\n" >${HOME}/getdns/usr/lib/pkgconfig/getdns.pc
 - sed -i -e 's/@/:/g' ${HOME}/getdns/usr/lib/pkgconfig/getdns.pc
 - sed -i -e 's/\[/${/g' ${HOME}/getdns/usr/lib/pkgconfig/getdns.pc
 - sed -i -e 's/]/}/g' ${HOME}/getdns/usr/lib/pkgconfig/getdns.pc
 - export PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:${HOME}/getdns/usr/lib/pkgconfig
 - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${HOME}/getdns/usr/lib/x86_64-linux-gnu
 - wget http://ftp.de.debian.org/debian/pool/main/o/openssl/libssl1.0.2_1.0.2h-1_amd64.deb
 - dpkg-deb -x libssl1.0.2_1.0.2h-1_amd64.deb ${HOME}/libssl
 - rm libssl1.0.2_1.0.2h-1_amd64.deb
 - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${HOME}/libssl/usr/lib/x86_64-linux-gnu
 - wget http://ftp.de.debian.org/debian/pool/main/u/unbound/libunbound2_1.5.8-1_amd64.deb
 - dpkg-deb -x libunbound2_1.5.8-1_amd64.deb ${HOME}/libunbound
 - rm libunbound2_1.5.8-1_amd64.deb
 - export PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:${HOME}/libunbound/usr/lib/pkgconfig
 - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${HOME}/libunbound/usr/lib/x86_64-linux-gnu
 - dig @208.67.222.222 a.root-servers.net
script:
 - autoreconf -i
 - ./configure
 - make
 - cd regression-tests
 - ./runtests
 - git status
 - git status | grep -q clean
notifications:
  irc:
    channels:
      - "irc.oftc.net#dovepower"
    template:
      - "%{author} @ %{repository} / %{branch} - Build:#%{build_number} : %{message} - Changes: %{compare_url} - Build details: %{build_url}"
    use_notice: true
    skip_join: true
